export interface Database {
  financial: {
    Tables: {
      products: {
        Row: {
          id: string;
          institution_id: string;
          name: string;
          product_code: string | null;
          category: string;
          subcategory: string | null;
          description: string | null;
          terms_and_conditions: string | null;
          min_amount: number | null;
          max_amount: number | null;
          interest_rate_min: number | null;
          interest_rate_max: number | null;
          rate_type: string | null;
          min_term_months: number | null;
          max_term_months: number | null;
          annual_fee: number | null;
          credit_limit_min: number | null;
          credit_limit_max: number | null;
          min_income: number | null;
          min_credit_score: number | null;
          max_credit_score: number | null;
          employment_requirement: string | null;
          collateral_required: boolean;
          accepts_imss: boolean;
          accepts_issste: boolean;
          requires_guarantor: boolean;
          is_active: boolean;
          is_featured: boolean;
          commission_rate: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          institution_id: string;
          name: string;
          product_code?: string | null;
          category: string;
          subcategory?: string | null;
          description?: string | null;
          terms_and_conditions?: string | null;
          min_amount?: number | null;
          max_amount?: number | null;
          interest_rate_min?: number | null;
          interest_rate_max?: number | null;
          rate_type?: string | null;
          min_term_months?: number | null;
          max_term_months?: number | null;
          annual_fee?: number | null;
          credit_limit_min?: number | null;
          credit_limit_max?: number | null;
          min_income?: number | null;
          min_credit_score?: number | null;
          max_credit_score?: number | null;
          employment_requirement?: string | null;
          collateral_required?: boolean;
          accepts_imss?: boolean;
          accepts_issste?: boolean;
          requires_guarantor?: boolean;
          is_active?: boolean;
          is_featured?: boolean;
          commission_rate?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          institution_id?: string;
          name?: string;
          product_code?: string | null;
          category?: string;
          subcategory?: string | null;
          description?: string | null;
          terms_and_conditions?: string | null;
          min_amount?: number | null;
          max_amount?: number | null;
          interest_rate_min?: number | null;
          interest_rate_max?: number | null;
          rate_type?: string | null;
          min_term_months?: number | null;
          max_term_months?: number | null;
          annual_fee?: number | null;
          credit_limit_min?: number | null;
          credit_limit_max?: number | null;
          min_income?: number | null;
          min_credit_score?: number | null;
          max_credit_score?: number | null;
          employment_requirement?: string | null;
          collateral_required?: boolean;
          accepts_imss?: boolean;
          accepts_issste?: boolean;
          requires_guarantor?: boolean;
          is_active?: boolean;
          is_featured?: boolean;
          commission_rate?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      institutions: {
        Row: {
          id: string;
          name: string;
          brand_name: string | null;
          institution_type: string;
          cnbv_license: string | null;
          condusef_registration: string | null;
          cnsf_registration: string | null;
          website: string | null;
          phone: string | null;
          email: string | null;
          street_address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          is_active: boolean;
          risk_rating: string | null;
          api_enabled: boolean;
          api_endpoint: string | null;
          webhook_endpoint: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          brand_name?: string | null;
          institution_type: string;
          cnbv_license?: string | null;
          condusef_registration?: string | null;
          cnsf_registration?: string | null;
          website?: string | null;
          phone?: string | null;
          email?: string | null;
          street_address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          is_active?: boolean;
          risk_rating?: string | null;
          api_enabled?: boolean;
          api_endpoint?: string | null;
          webhook_endpoint?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          brand_name?: string | null;
          institution_type?: string;
          cnbv_license?: string | null;
          condusef_registration?: string | null;
          cnsf_registration?: string | null;
          website?: string | null;
          phone?: string | null;
          email?: string | null;
          street_address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          is_active?: boolean;
          risk_rating?: string | null;
          api_enabled?: boolean;
          api_endpoint?: string | null;
          webhook_endpoint?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
  core: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          email_verified: boolean;
          phone: string | null;
          phone_verified: boolean;
          password_hash: string | null;
          password_salt: string | null;
          two_factor_enabled: boolean;
          two_factor_secret: string | null;
          first_name: string;
          last_name: string;
          middle_name: string | null;
          date_of_birth: string | null;
          gender: string | null;
          nationality: string;
          curp: string | null;
          rfc: string | null;
          ine_number: string | null;
          street_address: string | null;
          neighborhood: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string;
          employment_status: string | null;
          employer_name: string | null;
          job_title: string | null;
          monthly_income: number | null;
          income_source: string | null;
          kyc_status: string;
          kyc_level: number;
          kyc_approved_at: string | null;
          kyc_expires_at: string | null;
          status: string;
          risk_score: number;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
          last_ip_address: string | null;
          privacy_policy_accepted: boolean;
          privacy_policy_accepted_at: string | null;
          terms_accepted: boolean;
          terms_accepted_at: string | null;
          marketing_consent: boolean;
        };
        Insert: {
          id?: string;
          email: string;
          email_verified?: boolean;
          phone?: string | null;
          phone_verified?: boolean;
          password_hash?: string | null;
          password_salt?: string | null;
          two_factor_enabled?: boolean;
          two_factor_secret?: string | null;
          first_name: string;
          last_name: string;
          middle_name?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          nationality?: string;
          curp?: string | null;
          rfc?: string | null;
          ine_number?: string | null;
          street_address?: string | null;
          neighborhood?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          employment_status?: string | null;
          employer_name?: string | null;
          job_title?: string | null;
          monthly_income?: number | null;
          income_source?: string | null;
          kyc_status?: string;
          kyc_level?: number;
          kyc_approved_at?: string | null;
          kyc_expires_at?: string | null;
          status?: string;
          risk_score?: number;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          last_ip_address?: string | null;
          privacy_policy_accepted?: boolean;
          privacy_policy_accepted_at?: string | null;
          terms_accepted?: boolean;
          terms_accepted_at?: string | null;
          marketing_consent?: boolean;
        };
        Update: {
          id?: string;
          email?: string;
          email_verified?: boolean;
          phone?: string | null;
          phone_verified?: boolean;
          password_hash?: string | null;
          password_salt?: string | null;
          two_factor_enabled?: boolean;
          two_factor_secret?: string | null;
          first_name?: string;
          last_name?: string;
          middle_name?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          nationality?: string;
          curp?: string | null;
          rfc?: string | null;
          ine_number?: string | null;
          street_address?: string | null;
          neighborhood?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          employment_status?: string | null;
          employer_name?: string | null;
          job_title?: string | null;
          monthly_income?: number | null;
          income_source?: string | null;
          kyc_status?: string;
          kyc_level?: number;
          kyc_approved_at?: string | null;
          kyc_expires_at?: string | null;
          status?: string;
          risk_score?: number;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          last_ip_address?: string | null;
          privacy_policy_accepted?: boolean;
          privacy_policy_accepted_at?: string | null;
          terms_accepted?: boolean;
          terms_accepted_at?: string | null;
          marketing_consent?: boolean;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}