-- Production Seed Data: Financial Institutions
-- Mexican Financial Institutions for Raisket Platform

INSERT INTO financial.institutions (
    id, 
    name, 
    brand_name, 
    institution_type, 
    cnbv_license, 
    condusef_registration,
    website,
    phone,
    email,
    street_address,
    city,
    state,
    postal_code,
    is_active,
    risk_rating,
    api_enabled
) VALUES 

-- Major Mexican Banks
(
    uuid_generate_v4(),
    'Banco Nacional de México, S.A.',
    'Banamex',
    'bank',
    'CNBV-B-001',
    'CONDUSEF-B-001',
    'https://www.banamex.com',
    '+52 55 1226 2663',
    'contacto@banamex.com',
    'Av. Ejército Nacional 843',
    'Ciudad de México',
    'CDMX',
    '11520',
    true,
    'AAA',
    true
),

(
    uuid_generate_v4(),
    'Banco Bilbao Vizcaya Argentaria México, S.A.',
    'BBVA México',
    'bank',
    'CNBV-B-002',
    'CONDUSEF-B-002',
    'https://www.bbva.mx',
    '+52 55 5621 3434',
    'contacto@bbva.mx',
    'Av. Universidad 1200',
    'Ciudad de México',
    'CDMX',
    '03339',
    true,
    'AAA',
    true
),

(
    uuid_generate_v4(),
    'Banco Santander (México), S.A.',
    'Santander México',
    'bank',
    'CNBV-B-003',
    'CONDUSEF-B-003',
    'https://www.santander.com.mx',
    '+52 55 5269 2000',
    'contacto@santander.com.mx',
    'Av. Prolongación Paseo de la Reforma 500',
    'Ciudad de México',
    'CDMX',
    '01219',
    true,
    'AAA',
    true
),

(
    uuid_generate_v4(),
    'HSBC México, S.A.',
    'HSBC México',
    'bank',
    'CNBV-B-004',
    'CONDUSEF-B-004',
    'https://www.hsbc.com.mx',
    '+52 55 5721 2222',
    'contacto@hsbc.com.mx',
    'Av. Paseo de las Palmas 736',
    'Ciudad de México',
    'CDMX',
    '11000',
    true,
    'AA',
    true
),

(
    uuid_generate_v4(),
    'Scotiabank Inverlat, S.A.',
    'Scotiabank México',
    'bank',
    'CNBV-B-005',
    'CONDUSEF-B-005',
    'https://www.scotiabank.com.mx',
    '+52 55 5123 4567',
    'contacto@scotiabank.com.mx',
    'Av. Santa Fe 94',
    'Ciudad de México',
    'CDMX',
    '01210',
    true,
    'AA',
    true
),

(
    uuid_generate_v4(),
    'Banco Azteca, S.A.',
    'Banco Azteca',
    'bank',
    'CNBV-B-006',
    'CONDUSEF-B-006',
    'https://www.bancoazteca.com.mx',
    '+52 55 1720 7777',
    'contacto@bancoazteca.com.mx',
    'Av. Insurgentes Sur 3579',
    'Ciudad de México',
    'CDMX',
    '14000',
    true,
    'A',
    true
),

(
    uuid_generate_v4(),
    'Banorte - Banco Mercantil del Norte, S.A.',
    'Banorte',
    'bank',
    'CNBV-B-007',
    'CONDUSEF-B-007',
    'https://www.banorte.com',
    '+52 81 8319 5000',
    'contacto@banorte.com',
    'Av. Revolución 3000',
    'Monterrey',
    'Nuevo León',
    '64720',
    true,
    'AAA',
    true
),

(
    uuid_generate_v4(),
    'Banco Inbursa, S.A.',
    'Inbursa',
    'bank',
    'CNBV-B-008',
    'CONDUSEF-B-008',
    'https://www.inbursa.com',
    '+52 55 5625 9000',
    'contacto@inbursa.com',
    'Av. Insurgentes Sur 1685',
    'Ciudad de México',
    'CDMX',
    '03900',
    true,
    'AA',
    true
),

-- Major Fintech Companies
(
    uuid_generate_v4(),
    'Konfío, S.A.P.I. de C.V., SOFOM, E.N.R.',
    'Konfío',
    'fintech',
    'CNBV-SOFOM-001',
    'CONDUSEF-SOFOM-001',
    'https://www.konfio.mx',
    '+52 55 4162 8888',
    'contacto@konfio.mx',
    'Av. Santa Fe 482',
    'Ciudad de México',
    'CDMX',
    '01219',
    true,
    'A',
    true
),

(
    uuid_generate_v4(),
    'Kueski, S.A.P.I. de C.V., SOFOM, E.N.R.',
    'Kueski',
    'fintech',
    'CNBV-SOFOM-002',
    'CONDUSEF-SOFOM-002',
    'https://www.kueski.com',
    '+52 55 4162 5637',
    'contacto@kueski.com',
    'Av. Revolución 1267',
    'Ciudad de México',
    'CDMX',
    '01020',
    true,
    'A',
    true
),

(
    uuid_generate_v4(),
    'Credijusto, S.A.P.I. de C.V., SOFOM, E.N.R.',
    'Credijusto',
    'fintech',
    'CNBV-SOFOM-003',
    'CONDUSEF-SOFOM-003',
    'https://www.credijusto.com',
    '+52 55 4738 9100',
    'contacto@credijusto.com',
    'Av. Paseo de la Reforma 296',
    'Ciudad de México',
    'CDMX',
    '06600',
    true,
    'A',
    true
),

(
    uuid_generate_v4(),
    'Clip, S.A. de C.V.',
    'Clip',
    'fintech',
    'CNBV-FINTECH-001',
    'CONDUSEF-FINTECH-001',
    'https://www.clip.mx',
    '+52 55 4738 9200',
    'contacto@clip.mx',
    'Av. Insurgentes Sur 601',
    'Ciudad de México',
    'CDMX',
    '03100',
    true,
    'A',
    true
),

(
    uuid_generate_v4(),
    'Nu México, S.A. de C.V., SOFOM, E.N.R.',
    'Nu',
    'fintech',
    'CNBV-SOFOM-004',
    'CONDUSEF-SOFOM-004',
    'https://www.nu.com.mx',
    '+52 55 4162 8900',
    'contacto@nu.com.mx',
    'Av. Santa Fe 505',
    'Ciudad de México',
    'CDMX',
    '01219',
    true,
    'A',
    true
),

-- Credit Unions
(
    uuid_generate_v4(),
    'Caja Popular Mexicana',
    'Caja Popular Mexicana',
    'credit_union',
    'CNBV-SCAP-001',
    'CONDUSEF-SCAP-001',
    'https://www.cajapopularmexicana.com.mx',
    '+52 33 3669 0000',
    'contacto@cajapopularmexicana.com.mx',
    'Av. López Mateos Norte 755',
    'Guadalajara',
    'Jalisco',
    '44100',
    true,
    'A',
    false
),

(
    uuid_generate_v4(),
    'Caja Popular San Pablo',
    'Caja San Pablo',
    'credit_union',
    'CNBV-SCAP-002',
    'CONDUSEF-SCAP-002',
    'https://www.cajasanpablo.com.mx',
    '+52 844 411 8000',
    'contacto@cajasanpablo.com.mx',
    'Blvd. Venustiano Carranza 1918',
    'Saltillo',
    'Coahuila',
    '25280',
    true,
    'A',
    false
),

-- Insurance Companies
(
    uuid_generate_v4(),
    'Seguros Monterrey New York Life, S.A. de C.V.',
    'Monterrey New York Life',
    'insurance',
    'CNSF-S-001',
    'CONDUSEF-S-001',
    'https://www.mtnyl.com.mx',
    '+52 81 8389 5000',
    'contacto@mtnyl.com.mx',
    'Av. Gómez Morín 344',
    'Monterrey',
    'Nuevo León',
    '66269',
    true,
    'AA',
    true
),

(
    uuid_generate_v4(),
    'Seguros Banorte Generali, S.A. de C.V.',
    'Banorte Generali',
    'insurance',
    'CNSF-S-002',
    'CONDUSEF-S-002',
    'https://www.banortegenerali.com',
    '+52 55 5004 4444',
    'contacto@banortegenerali.com',
    'Av. Cerro de las Torres 395',
    'Ciudad de México',
    'CDMX',
    '10200',
    true,
    'AA',
    true
),

(
    uuid_generate_v4(),
    'Qualitas Compañía de Seguros, S.A. de C.V.',
    'Quálitas',
    'insurance',
    'CNSF-S-003',
    'CONDUSEF-S-003',
    'https://www.qualitas.com.mx',
    '+52 55 1103 3000',
    'contacto@qualitas.com.mx',
    'Av. San Jerónimo 1029',
    'Ciudad de México',
    'CDMX',
    '10200',
    true,
    'A',
    true
),

-- AFORE Companies
(
    uuid_generate_v4(),
    'AFORE XXI Banorte, S.A. de C.V.',
    'AFORE XXI Banorte',
    'afore',
    'CONSAR-A-001',
    'CONDUSEF-A-001',
    'https://www.aforexxibanorte.com',
    '+52 55 5004 5555',
    'contacto@aforexxibanorte.com',
    'Av. Cerro de las Torres 395',
    'Ciudad de México',
    'CDMX',
    '10200',
    true,
    'AAA',
    false
),

(
    uuid_generate_v4(),
    'AFORE Coppel, S.A. de C.V.',
    'AFORE Coppel',
    'afore',
    'CONSAR-A-002',
    'CONDUSEF-A-002',
    'https://www.aforecoppel.com',
    '+52 667 759 1000',
    'contacto@aforecoppel.com',
    'Av. Álvaro Obregón 1891',
    'Culiacán',
    'Sinaloa',
    '80020',
    true,
    'A',
    false
);

-- Update created_at and updated_at timestamps
UPDATE financial.institutions 
SET created_at = NOW(), updated_at = NOW() 
WHERE created_at IS NULL;